### **Análise dos dados**

Segue abaixo a análise dos dados inicialmente fornecidos.

Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix
import seaborn as sns

import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# LSTM Teste 1

In [3]:
df = pd.read_csv('../data/preparacao_modelo_1.csv')
df

,KNR,ID1NAME,ID1SOK,ID1SNOK,ID1DATA,ID2NAME,ID2SOK,ID2SNOK,ID2DATA,ID718NAME,ID718SOK,ID718SNOK,ID718DATA,FALHA
0,2023-2016173,0.0,0.0,0.0,0.0,0.010733,0.010791,0.0,3.736757e-06,0.005038,0.003546,0.004405,0.000047,0.0
1,2023-2026098,0.0,0.0,0.0,0.0,0.007156,0.007194,0.0,1.868379e-07,0.002519,0.003546,0.000000,0.000000,0.0
2,2023-2026162,0.0,0.0,0.0,0.0,0.007156,0.007194,0.0,9.341893e-07,0.002519,0.003546,0.000000,0.000000,0.0
3,2023-2026175,0.0,0.0,0.0,0.0,0.007156,0.007194,0.0,1.121027e-06,0.002519,0.003546,0.000000,0.000000,0.0
4,2023-2026215,0.0,0.0,0.0,0.0,0.007156,0.007194,0.0,9.341893e-07,0.002519,0.003546,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,2024-2976009,0.0,0.0,0.0,0.0,0.064401,0.064748,0.0,7.374491e-04,0.000000,0.000000,0.000000,0.000000,0.0
49187,2024-2976010,0.0,0.0,0.0,0.0,0.064401,0.064748,0.0,9.554889e-04,0.000000,0.000000,0.000000,0.000000,1.0
49188,2024-2976011,0.0,0.0,0.0,0.0,0.066190,0.066547,0.0,1.438091e-03,0.000000,0.000000,0.000000,0.000000,1.0
49189,2024-2976012,0.0,0.0,0.0,0.0,0.073345,0.073741,0.0,6.931648e-02,0.000000,0.000000,0.000000,0.000000,1.0
49190,2024-2976013,0.0,0.0,0.0,0.0,0.064401,0.064748,0.0,8.796327e-04,0.000000,0.000000,0.000000,0.000000,1.0

In [6]:
# Separando as features (X) e o target (y)
X = df.drop(columns=['FALHA', 'KNR'])  # 'KNR' é apenas um identificador, então deve ser removido
Y = df['FALHA']

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [17]:
X_train = np.array(X_train)
X_test = np.array(X_test)

X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

In [19]:
model = Sequential()

model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(X_train.shape[1], 1)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')

In [ ]:
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, ConfusionMatrixDisplay

# Prever os dados de teste
y_pred = model.predict(X_test)

# Converter as probabilidades em classes binárias (0 ou 1)
y_pred_classes = (y_pred > 0.5).astype(int)

# Calcular as principais métricas
accuracy = accuracy_score(y_test, y_pred_classes)
precision = precision_score(y_test, y_pred_classes)
recall = recall_score(y_test, y_pred_classes)
f1 = f1_score(y_test, y_pred_classes)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

# Matriz de Confusão
cm = confusion_matrix(y_test, y_pred_classes)

# Exibindo a Matriz de Confusão
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.show()

In [ ]:
model.save('Keras_YN.h5')